version: "3"

services:
  db:
    container_name: authjwt_db
    image: postgres:13.3
    restart: on-failure
    volumes: 
      - ./postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
      - POSTGRES_DB=$DATABASE_NAME
      - POSTGRES_USER=$DATABASE_USERNAME
      - POSTGRES_PASSWORD=$DATABASE_PASSWORD
    
    ports:
      - $DATABASE_PORT:$DATABASE_PORT

  node_api:
    container_name: app
    build: ./backend
    volumes:
      - ./backend:/app
    ports:
      - $API_PORT:$API_PORT
    depends_on:
      - db
    restart: on-failure

  react_app:
    container_name: frontent
    build: ./frontend
    volumes:
      - ./frontend:/app
    ports:
      - 8081:8081
    depends_on:
      - node_api
